### ISSUE TITLE
Deadlock pri cteni vetsich souboru rourou

### ISSUE THREAD

**Issue by Cajova-Houba** [Cajova-Houba/kiv-os-simulator#11]
Replikace:
1. vytvořit si velky soubor, třeba `rgen > f.txt`
2. poslat to rourou do freq `type f.txt | freq`
3. deadlock

Proč:
(Nejspíš) čtecí konec roury čeká na mutexu (pipe.cpp:127) když je buffer prázdný. Zapisovací konec mezitím pushuje data (4096 bytů) do bufferu čtecího konce, který má velikost 1024. Buffer čtecího konce se naplní a čeká na mutexu na vyprázdnění (pipe.cpp:41). Push metoda volá notify() (pipe.cpp:73) nad mutexem až po zapsání celého bloku dat, v tom asi bude ta příčina.

**Comment by ccomrade** [comment]
Opraveno.
