### ISSUE TITLE
Zapis na zacatek souboru pri presmerovani >>

### ISSUE THREAD

**Issue by Cajova-Houba** [Cajova-Houba/kiv-os-simulator#12]
Když se použije přesměrování >> tak se nenastavuje pozice v souboru na jeho konec (asi by to mělo být v `Shell::prepareFiles::398`), takže se zapisuje od začátku souboru. Je to záměr, nebo chyba?

**Comment by ccomrade** [comment]
Rozhodně chyba.

**Comment by ccomrade** [comment]
Opraveno.
