### ISSUE TITLE
Odevzdání

### ISSUE THREAD

**Issue by ccomrade** [Cajova-Houba/kiv-os-simulator#13]
Už bych to teda odevzdal. Chceš to odevzdat ty nebo to mam poslat já? Správně by to asi měla odevzdat @nezka jako vedoucí týmu, ale snad nebude vadit, když to odevzdá jeden z nás.

Odevzdávat se má jen:
```
doc/dokumentace.pdf
src/boot/...
src/kernel/...
src/user/...
```

**Comment by Cajova-Houba** [comment]
Klidně to odevzdej ty. Ještě jsem tam opravil tu titulní stránku, tak jestli je to takhle dobrý, už bych to asi nechal být. Napadlo mě tam teda ještě dodělat pát sekvenčních diagramů ohledně API nad procesama/vláknama, ale je to všechno víceméně podobný, tak mi to přijde zbytečný.

**Comment by ccomrade** [comment]
OK. Ještě to pro jistotu zkusim předhodit tomu validátoru a potom to odevzdam.

Odevzdává se to přes ten ZČU Portál, ne?

**Comment by Cajova-Houba** [comment]
Jo jo, na portálu. Ale ještě počkej, na courseware je napsáno, že v dokumentaci mají být i studijní čísla. Tak mi ho sem prosím napiš a já je tam dodam.

**Comment by ccomrade** [comment]
A19N0076P

**Comment by Cajova-Houba** [comment]
Doděláno. Anežky osobní číslo nemám, ale to asi ani nevadí, když končí.

**Comment by ccomrade** [comment]
Anežka má A19N0077P.

**Comment by Cajova-Houba** [comment]
Tak snad už teď je to všechno.

**Comment by ccomrade** [comment]
Validátorem to projde:

```
Exit code: 0x0

Execution time: 0:0.525570 [min:sec]
Kernel time: 0:0.000000 [min:sec]
User time: 0:0.000000 [min:sec]
Time limit exceeded: no

Peak memory used: 676 kB
Page fault count: 992

Excessive files count: 0
Excessive files size: 0 kB
```

**Comment by ccomrade** [comment]
Odevzdáno.
