### ISSUE TITLE
Volání příkazů z shellu

### ISSUE THREAD

**Issue by Cajova-Houba** [Cajova-Houba/kiv-os-simulator#4]
Jak přesně se mají volat příkazy (echo, md, ...) z `shell.cpp`?

**Comment by ccomrade** [comment]
Shell musí nejprve rozparsovat to, co mu zadá uživatel. Příklad:
```
type soubor.txt | sort > neco.txt
```

V tomto případě uživatel chce vypsat obsah souboru `soubor.txt`, ten předat příkazu `sort` a výsledek zapsat do souboru `neco.txt`. Takže shell musí:

1. Otevřít nebo vytvořit soubor `neco.txt`. Pokud už existuje, tak odstranit to, co v něm je, a nastavit pozici na nulu. Takto se chová `>`. Pokud by tam bylo `>>`, tak se obsah souboru zachová a pozice se nastaví na jeho konec (tj. výstup příkazu se jen přidá na konec souboru).
2. Vytvořit rouru pro přenos výstupu z příkazu `type` na vstup příkazu `sort`.
3. Vytvořit proces příkazu `sort`, kde standardní výstup bude handle souboru `neco.txt` a standardní vstup bude výstup té roury.
4. Vytvořit proces příkazu `type`, kde standardní výstup bude vstup té roury, a předat mu `soubor.txt` jako parametr.
5. Počkat až `type` skončí a zavřít zapisovací konec roury.
6. Počkat až `sort` skončí.
7. Uklidit po sobě :)

Tohle všechno je potřeba nějak zobecnit, aby to shell uměl vykonat pro jakýkoliv vstup od uživatele.

Tady ještě na ukázku kód k tomu příkladu:
```c++
// otevřeme nebo vytvoříme výstupní soubor
kiv_os::THandle outputFile = RTL::OpenFile("neco.txt", 0, 0);
if (!outputFile)
{
	// error
}

// nastavíme pozici a velikost výstupního souboru na nulu
// tím se odstraní případný obsah, pokud výstupní soubor už existuje
int64_t pos = 0;
if (!RTL::SeekFile(outputFile, kiv_os::NFile_Seek::Set_Size, kiv_os::NFile_Seek::Beginning, pos))
{
	// error
}

// vytvoříme rouru
Pipe pipe = RTL::CreatePipe();
if (!pipe)
{
	// error
}

// nastavíme prostředí příkazu "sort"
RTL::ProcessEnvironment sortEnv;
sortEnv.stdOut = outputFile;
sortEnv.stdIn = pipe.readEnd;

// a spustíme příkaz "sort"
kiv_os::THandle sortProcess = RTL::CreateProcess("sort", sortEnv);
if (!sortProcess)
{
	// error
}

// parametry příkazu "type"
std::string typeArgs = "program.txt";

// nastavíme prostředí příkazu "type"
RTL::ProcessEnvironment typeEnv;
typeEnv.stdOut = pipe.writeEnd;
typeEnv.stdIn = RTL::GetStdInHandle();
typeEnv.cmdLine = typeArgs.c_str();

// a spustíme příkaz "type"
kiv_os::THandle typeProcess = RTL::CreateProcess("type", typeEnv);
if (!typeProcess)
{
	// error
}

// v tuto chvíli příkaz "type" čte vstupní soubor a posílá obsah do roury
// na druhé straně roury potom čeká na data příkaz "sort"

// počkáme až "type" skončí
if (RTL::WaitFor(&typeProcess, 1) < 0)
{
	// error
}

// zavřeme zapisovací konec roury, takže "sort" se dozví,
// že už mu nic dalšího nepřijde a může skončit
RTL::CloseHandle(pipe.writeEnd);

// počkáme až "sort" skončí
if (RTL::WaitFor(&sortProcess, 1) < 0)
{
	// error
}

// úklid
RTL::CloseHandle(typeProcess);
RTL::CloseHandle(sortProcess);
RTL::CloseHandle(pipe.readEnd);
RTL::CloseHandle(outputFile);
```

Když se tak dívám na ten kód, tak ještě bude potřeba v RTL upravit několik věcí, aby to bylo pěkné.
Taky by to asi chtělo vytvořit vlastní definice těch věcí z `api.h` (který teda nemůžeme měnit), protože například `kiv_os::THandle` nebo `kiv_os::NFile_Seek::Set_Size` vypadá hrozně.

**Comment by Cajova-Houba** [comment]
Jo, paráda. To vypadá rozumně.

**Comment by ccomrade** [comment]
Jsem teda RTL ještě trochu uklidil, takže teď už by to mělo být OK.

Tady je aktualizovaný kód toho příkladu:
```c++
RTL::File outputFile;
// otevřeme nebo vytvoříme výstupní soubor
if (!outputFile.create("neco.txt"))
{
	// error
}

// nastavíme pozici a velikost výstupního souboru na nulu
// tím se odstraní případný obsah, pokud výstupní soubor už existuje
if (!outputFile.setSize(0))
{
	// error
}

// vytvoříme rouru
RTL::Pipe pipe = RTL::CreatePipe();
if (!pipe)
{
	// error
}

RTL::Process sort;
sort.name = "sort";
sort.stdIn = pipe.readEnd;
sort.stdOut = outputFile.handle;

// spustíme příkaz "sort"
if (!sort.start())
{
	// error
}

RTL::Process type;
type.name = "type";
type.stdIn = RTL::GetStdInHandle();
type.stdOut = pipe.writeEnd;
type.cmdLine = "soubor.txt";

if (!type.start())
{
	// error
}

// v tuto chvíli příkaz "type" čte vstupní soubor a posílá obsah do roury
// na druhé straně roury potom čeká na data příkaz "sort"

// počkáme až "type" skončí
if (!type.waitFor())
{
	// error
}

// zavřeme zapisovací konec roury, takže "sort" se dozví,
// že už mu nic dalšího nepřijde a může skončit
pipe.closeWriteEnd();

// počkáme až "sort" skončí
if (!sort.waitFor())
{
	// error
}

// úklid je teď automatický :)
```

Jak jsem to psal narychlo, tak v tom příkladu bylo několik drobných chyb. Tohle už je snad v pořádku.
