### ISSUE TITLE
Příkaz pro odstranění souboru?

### ISSUE THREAD

**Issue by ccomrade** [Cajova-Houba/kiv-os-simulator#7]
V seznamu příkazů, které máme implementovat, chybí příkaz pro odstranění souboru. Například `del`, `erase` nebo `rm`. Je tam jen `rd` pro odstranění adresáře. Co s tím?

**Comment by Cajova-Houba** [comment]
@ccomrade 
No, jestli na to nebylo nic ani v kostře, tak bych to neimplementoval (nebo bych se případně zeptal na další přednášce). Jinak mam podobnej dotaz na změnu velikosti souboru, využívá to nějakej příkaz? Jestli ne, tak to neni nutný implementovat. Co přesně máš teď rozdělaný? Mám trochu času tak dodělám zbytek.

**Comment by ccomrade** [comment]
Zatím to bude tak, že příkaz `rd` bude odstraňovat i soubory.

Změna velikosti souboru je potřeba při přesměrování výstupu příkazu do existujícího souboru (shell nastaví velikost souboru na 0 a tím odstraní existující obsah).

Jsem teď dokončil všechnu rozdělanou práci a commitnul to. Už chybí jen několik příkazů a nadrátovat tu FATku.

**Comment by Cajova-Houba** [comment]
@ccomrade 

Dobře, resize jsem doimplementoval.

Všiml jsem si, že v zadání nejsou k příkazu `rd`, žádné parametry (`/S`). Budeme nějak řešit rekurzivní mazání adresářů a jestli jo, tak na úrovni implementace příkazu `rd`, nebo už v `FatFs.remove()`? ~Nejjednodušší by asi bylo mazat soubory a prázdné adresáře a v případě neprázdných adresářů prostě vrátit chybu.~

Edit: ok

**Comment by ccomrade** [comment]
Náš `rd` už parametr `/S` podporuje. Rekurzivní odstranění obsahu adresáře řeší RTL.

**Comment by Cajova-Houba** [comment]
@ccomrade 
Ještě jedna věc ohledně `rd`. Když bude bez `/S`, kde budeme kontrolovat, že adresář není prázdný? V RTL, nebo v ovladači fatky?

**Comment by ccomrade** [comment]
`IFileSystem::remove` by měl fungovat tak, že odstraní jen soubor nebo prázdný adresář. Pokud adresář k odstranění není prázdný, tak error (`EStatus::DIRECTORY_NOT_EMPTY`).

**Comment by Cajova-Houba** [comment]
Ok
