### ISSUE TITLE
Kernel deadlock

### ISSUE THREAD

**Issue by ccomrade** [Cajova-Houba/kiv-os-simulator#8]
Občas při velké zátěži dojde v jádře k deadlocku, takže celý systém zamrzne.

**Comment by Cajova-Houba** [comment]
Máš nějakej script, kterým to testuješ?

**Comment by ccomrade** [comment]
Testuju to ručně. Například pomocí `rgen | type | type | type | type | freq`. :)

Jinak už je to opravený. Byla tam menší chyba ve funkci pro čtení z roury, kde plnou rouru to považovalo za prázdnou.
