### ISSUE TITLE
Dokumentace

### ISSUE THREAD

**Issue by Cajova-Houba** [Cajova-Houba/kiv-os-simulator#9]

**Comment by Cajova-Houba** [comment]
@ccomrade No, už mi pomalu docházejí nápady, tak si to prosím pročti a kdyby tě něco napadlo, tak to tam buď přímo napiš, nebo to napiš sem do komentáře.

**Comment by ccomrade** [comment]
Pracuju na tom.

Ještě by to možná chtělo něco udělat s tou tabulkou (jména a datum) na úvodní straně. Ten datum na konci řádky tam vypadá divně.

**Comment by ccomrade** [comment]
Tak jsem tam teda něco dopsal a opravil pár nepřesností.
